### ISSUE TITLE
smooth

### ISSUE THREAD

**Issue by tenSunFree** [iammert/ScalingLayout#1]
![2017-10-05_010049](https://user-images.githubusercontent.com/23090085/31188845-f5dc1996-a968-11e7-8760-955b25dc3192.jpg)

The edge does not seem so smooth?

Is there a way to solve it?

**Comment by iammert** [comment]
Is it the screenshot from gif in the readme file?

**Comment by tenSunFree** [comment]
This is a picture that is displayed on the phone

**Comment by Cricin** [comment]
canvas.clipPath() is not anti-alias, and this clip with round rect is heavy operation

**Comment by iammert** [comment]
Yes, It looks like anti-alias problem. I am going to fix that issue asap.
