### ISSUE TITLE
onProgress()

### ISSUE THREAD

**Issue by tenSunFree** [iammert/ScalingLayout#11]
![2017-10-12_013633](https://user-images.githubusercontent.com/23090085/31457044-2f8c94ec-aeee-11e7-8e91-09bc629bff85.jpg)

![2017-10-12_013830](https://user-images.githubusercontent.com/23090085/31457056-33adea26-aeee-11e7-996b-e88822aba01e.jpg)

Is it superfluous?

**Comment by iammert** [comment]
Yes, you are right. I didn't notice the mistake. I will change it.

**Comment by tenSunFree** [comment]
![2017-10-13_104941](https://user-images.githubusercontent.com/23090085/31528298-feeceaae-b004-11e7-8965-c9896818cedc.jpg)

![2017-10-13_105101](https://user-images.githubusercontent.com/23090085/31528302-0389d338-b005-11e7-8076-c5363846719a.jpg)

Because of Progress value is between 0 and 1
So A with B should be the same?

**Comment by iammert** [comment]
Yes, A and B are same. 1 means that your scaling layout expanded totaly. 0 means that layout is in the initial position.
