### ISSUE TITLE
Not run on below API 21

### ISSUE THREAD

**Issue by tellfa** [iammert/ScalingLayout#19]
Hi, thanks for this library,
but when run application on below api 21 show me this error : 

`    Process: iammert.com.view.scalinglayout, PID: 2090
    java.lang.NoClassDefFoundError: iammert.com.view.scalinglib.ScalingLayoutOutlineProvider
        at iammert.com.view.scalinglib.ScalingLayout.onSizeChanged(ScalingLayout.java:156)`

Can you fix it?

**Comment by tellfa** [comment]
hey @iammert can you help us?

**Comment by tellfa** [comment]
@athulantonynp yes dear friend i write codes such as this. but this effect is awesome I wish they could use the lower Androids

**Comment by iammert** [comment]
Fixed. use version 1.2.1.
