### ISSUE TITLE
Tiny mistake: wrong icon for the sorting...

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [iammert/ScalingLayout#3]
You use the one of filtering, and not of sorting, in the sample.

**Comment by iammert** [comment]
Yes, you are right :) I am closing this issue because this is just a demo, no implementation behind it :) Thanks for the feedback again :)

**Comment by AndroidDeveloperLB** [comment]
So have you fixed it?

**Comment by iammert** [comment]
https://github.com/iammert/ScalingLayout/commit/9911ff9091dca07793af134e5b8fea562cb1814b

**Comment by AndroidDeveloperLB** [comment]
ok.
